"""initial_migration

Revision ID: 63551604b9fd
Revises: 
Create Date: 2025-10-22 05:19:42.487939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63551604b9fd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###