using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace VoiceStudio.UI.Pages
{
    public class ABComparePageModel : PageModel
    {
        public string EvalDir { get; private set; } = string.Empty;
        public bool AExists { get; private set; }
        public bool BExists { get; private set; }
        public bool DiffExists { get; private set; }
        public string? Message { get; private set; }

        public void OnGet()
        {
            EvalDir = GetEvalDir();
            AExists = System.IO.File.Exists(Path.Combine(EvalDir, "A.wav"));
            BExists = System.IO.File.Exists(Path.Combine(EvalDir, "B.wav"));
            DiffExists = System.IO.File.Exists(Path.Combine(EvalDir, "diff.wav"));
        }

        public IActionResult OnPostNull()
        {
            EvalDir = GetEvalDir();
            var aPath = Path.Combine(EvalDir, "A.wav");
            var bPath = Path.Combine(EvalDir, "B.wav");
            var outPath = Path.Combine(EvalDir, "diff.wav");
            if (!System.IO.File.Exists(aPath) || !System.IO.File.Exists(bPath))
            {
                Message = "A.wav or B.wav not found in eval directory.";
                OnGet();
                return Page();
            }

            try
            {
                CreateNullDiff(aPath, bPath, outPath);
                Message = "Null diff created: diff.wav";
            }
            catch (Exception ex)
            {
                Message = "Error: " + ex.Message;
            }

            OnGet();
            return Page();
        }

        private static string GetEvalDir()
        {
            var programData = Environment.GetEnvironmentVariable("PROGRAMDATA");
            string baseDir;
            if (!string.IsNullOrWhiteSpace(programData)) baseDir = Path.Combine(programData, "VoiceStudio");
            else
            {
                var common = Environment.GetFolderPath(Environment.SpecialFolder.CommonApplicationData);
                if (string.IsNullOrWhiteSpace(common)) common = AppContext.BaseDirectory;
                baseDir = Path.Combine(common, "VoiceStudio");
            }
            var evalDir = Path.Combine(baseDir, "eval");
            Directory.CreateDirectory(evalDir);
            return evalDir;
        }

        private static void CreateNullDiff(string aPath, string bPath, string outPath)
        {
            using var fa = System.IO.File.OpenRead(aPath);
            using var fb = System.IO.File.OpenRead(bPath);
            using var ra = new BinaryReader(fa);
            using var rb = new BinaryReader(fb);

            // Read 44-byte PCM WAV headers (as generated by the eval script)
            byte[] ha = ra.ReadBytes(44);
            byte[] hb = rb.ReadBytes(44);
            if (ha.Length < 44 || hb.Length < 44) throw new InvalidDataException("Invalid WAV headers");

            using var fo = System.IO.File.Open(outPath, FileMode.Create, FileAccess.ReadWrite, FileShare.Read);
            using var bw = new BinaryWriter(fo);
            // Write header placeholder from A
            bw.Write(ha);

            long restA = fa.Length - 44;
            long restB = fb.Length - 44;
            long minBytes = Math.Min(restA, restB);
            long sampleCount = minBytes / 2; // 16-bit mono

            for (long i = 0; i < sampleCount; i++)
            {
                short sa = ra.ReadInt16();
                short sb = rb.ReadInt16();
                int diff = sa - sb;
                if (diff > short.MaxValue) diff = short.MaxValue;
                if (diff < short.MinValue) diff = short.MinValue;
                bw.Write((short)diff);
            }

            bw.Flush();
            long dataSize = sampleCount * 2;
            // Fix data chunk size at offset 40
            fo.Position = 40;
            bw.Write(BitConverter.GetBytes((int)dataSize));
            // Fix RIFF chunk size at offset 4 (file size - 8)
            fo.Position = 4;
            int riffSize = (int)(44 + dataSize - 8);
            bw.Write(BitConverter.GetBytes(riffSize));
        }
    }
}
