<#
.SYNOPSIS
    Binary search to isolate problematic XAML file(s) that cause the WinUI XAML compiler to fail.
    
.DESCRIPTION
    This script reads the input.json used by the XAML compiler, splits the XamlPages in half,
    and tests each half to find which file(s) cause the compiler to crash silently.
    
.PARAMETER InputJsonPath
    Path to the input.json file generated by MSBuild for the XAML compiler.
    
.PARAMETER OutputDir
    Directory to write test input/output JSON files.
    
.EXAMPLE
    .\scripts\xaml-binary-search.ps1
#>

param(
    [string]$InputJsonPath = "E:\VoiceStudio\src\VoiceStudio.App\obj\x64\Debug\net8.0-windows10.0.19041.0\win-x64\input.json",
    [string]$OutputDir = "E:\VoiceStudio\.buildlogs\xaml-bisect"
)

$ErrorActionPreference = "Stop"

# Ensure output directory exists
New-Item -ItemType Directory -Path $OutputDir -Force | Out-Null

# Read the original input.json
Write-Host "Reading $InputJsonPath..."
$originalJson = Get-Content $InputJsonPath -Raw | ConvertFrom-Json

# Get the XAML compiler path
$nugetRoot = if ($env:NUGET_PACKAGES) { $env:NUGET_PACKAGES } else { "$env:USERPROFILE\.nuget\packages" }
$compilerPath = Get-ChildItem "$nugetRoot\microsoft.windowsappsdk.winui\*\tools\net472\XamlCompiler.exe" -ErrorAction SilentlyContinue | 
    Sort-Object { $_.Directory.Parent.Name } | 
    Select-Object -Last 1 -ExpandProperty FullName

if (-not $compilerPath) {
    Write-Error "Could not find XamlCompiler.exe"
    exit 1
}

Write-Host "Using compiler: $compilerPath"

$allPages = @($originalJson.XamlPages)
Write-Host "Total XAML pages: $($allPages.Count)"

function Test-XamlSubset {
    param(
        [array]$Pages,
        [string]$Label
    )
    
    if ($Pages.Count -eq 0) {
        return $true
    }
    
    # Create a modified input.json with only the specified pages
    $testJson = $originalJson.PSObject.Copy()
    $testJson.XamlPages = $Pages
    
    $inputPath = Join-Path $OutputDir "input_$Label.json"
    $outputPath = Join-Path $OutputDir "output_$Label.json"
    
    # Remove old output
    if (Test-Path $outputPath) { Remove-Item $outputPath -Force }
    
    # Write test input
    $testJson | ConvertTo-Json -Depth 20 | Set-Content $inputPath -Encoding UTF8
    
    # Run compiler
    Push-Location "E:\VoiceStudio\src\VoiceStudio.App"
    try {
        $process = Start-Process -FilePath $compilerPath -ArgumentList "`"$inputPath`"", "`"$outputPath`"" -Wait -PassThru -NoNewWindow
        $exitCode = $process.ExitCode
    }
    finally {
        Pop-Location
    }
    
    # Check result
    if ($exitCode -eq 0 -or (Test-Path $outputPath)) {
        Write-Host "  [$Label] PASS ($($Pages.Count) pages)"
        return $true
    }
    else {
        Write-Host "  [$Label] FAIL ($($Pages.Count) pages)"
        return $false
    }
}

function Find-ProblematicFiles {
    param(
        [array]$Pages
    )
    
    if ($Pages.Count -eq 0) {
        return @()
    }
    
    if ($Pages.Count -eq 1) {
        # Single file - test it
        $label = ($Pages[0].ItemSpec -replace '[\\/:*?"<>|]', '_')
        if (-not (Test-XamlSubset -Pages $Pages -Label "single_$label")) {
            Write-Host "  FOUND PROBLEMATIC FILE: $($Pages[0].ItemSpec)" -ForegroundColor Red
            return @($Pages[0].ItemSpec)
        }
        return @()
    }
    
    # Split in half
    $mid = [math]::Floor($Pages.Count / 2)
    $firstHalf = $Pages[0..($mid-1)]
    $secondHalf = $Pages[$mid..($Pages.Count-1)]
    
    $label = "batch_$($Pages.Count)"
    
    $problems = @()
    
    # Test first half
    Write-Host "Testing first half ($($firstHalf.Count) pages)..."
    if (-not (Test-XamlSubset -Pages $firstHalf -Label "${label}_first")) {
        $problems += Find-ProblematicFiles -Pages $firstHalf
    }
    
    # Test second half
    Write-Host "Testing second half ($($secondHalf.Count) pages)..."
    if (-not (Test-XamlSubset -Pages $secondHalf -Label "${label}_second")) {
        $problems += Find-ProblematicFiles -Pages $secondHalf
    }
    
    return $problems
}

# First, test if the full set fails
Write-Host "`nTesting full set of $($allPages.Count) pages..."
if (Test-XamlSubset -Pages $allPages -Label "full") {
    Write-Host "`nFull set PASSED - no problematic files found!" -ForegroundColor Green
    exit 0
}

Write-Host "`nFull set FAILED - starting binary search..." -ForegroundColor Yellow

# Run binary search
$problematicFiles = Find-ProblematicFiles -Pages $allPages

Write-Host "`n========================================" -ForegroundColor Cyan
Write-Host "BINARY SEARCH COMPLETE" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan

if ($problematicFiles.Count -eq 0) {
    Write-Host "No individual problematic files found." -ForegroundColor Yellow
    Write-Host "The issue may be a combination of files or a resource dictionary problem."
}
else {
    Write-Host "Problematic files found:" -ForegroundColor Red
    $problematicFiles | ForEach-Object { Write-Host "  - $_" -ForegroundColor Red }
    
    # Save results
    $resultsPath = Join-Path $OutputDir "problematic_files.txt"
    $problematicFiles | Set-Content $resultsPath
    Write-Host "`nResults saved to: $resultsPath"
}
