namespace VoiceStudio.Core.Events
{
  /// <summary>
  /// Event raised when audio is generated by any module.
  /// Allows cross-module reactions (e.g., Analysis module can analyze Voice module output).
  /// </summary>
  public sealed class AudioGeneratedEvent
  {
    /// <summary>
    /// Unique identifier for the generated audio.
    /// </summary>
    public string AudioId { get; init; } = string.Empty;

    /// <summary>
    /// The module that generated the audio (e.g., "Voice", "Media").
    /// </summary>
    public string SourceModule { get; init; } = string.Empty;

    /// <summary>
    /// Optional file path if audio was saved to disk.
    /// </summary>
    public string? FilePath { get; init; }

    /// <summary>
    /// Audio duration in seconds.
    /// </summary>
    public double DurationSeconds { get; init; }

    /// <summary>
    /// Engine used for generation (e.g., "xtts", "piper").
    /// </summary>
    public string? EngineId { get; init; }
  }
}